documentation is deprecated, change it to window documentation
LunarVim/Neovim-from-scratch pull request #115
Opened 2022-04-17 00:08 UTC by John15321

for some reason it's deprecated, I found it while following your tutorial. Written this way u don't get an error

https://github.com/hrsh7th/nvim-cmp/issues/231

2022-04-22 01:10 UTC, aflyingpumpkin commented
This appears to be a duplicate of #112

2022-04-23 05:16 UTC, VAISHAKH-GK approved these changes

2022-05-09 13:22 UTC, gnmearacaun requested changes
You seem to have an extra bracket on line 123

2022-05-10 06:23 UTC, VAISHAKH-GK commented
> You seem to have an extra bracket on line 123

No , documentation is inside window that's why 2 curly braces ( 3 including border ).

2022-05-10 12:17 UTC, gnmearacaun requested changes
Okay, but there's a comma missing after the curly brace on line 123

2022-05-10 12:23 UTC, VAISHAKH-GK commented
> Okay, but there's a comma missing after the curly brace on line 123

No since Documentation is inside window only needed coma after the closing curly brace of window it have that.

2022-05-10 12:42 UTC, gnmearacaun commented
Okay, I am normally seeing `},` except for `}` at the end of setups usually

2022-05-31 19:35 UTC, gnmearacaun commented
#146 appears to have fixed this. If so, please close the PR tyvm

2022-06-13 17:34 UTC, closed without merging