Removed deprecated code from `cmp.lua`
LunarVim/Neovim-from-scratch pull request #117
Opened 2022-04-19 18:07 UTC by aflyingpumpkin

While going through the tutorial I noticed some messages from `nvim-cmp` yelling at me for using deprecated code this fixes that issue.

2022-04-21 09:04 UTC, josephsv96 approved these changes

2022-04-22 01:09 UTC, aflyingpumpkin commented
Just looked at the other PRs looks like I am not the only one who has noticed this issue (#115 and #112). I believe this approach is the best because it a good bit simpler.

2022-05-02 09:57 UTC, gnmearacaun requested changes
you're missing a comment `,` after curly brace on line 122. It should be 
```
  window = {
    documentation = cmp.config.window.bordered(),
  },
```

2022-05-09 13:24 UTC, gnmearacaun requested changes
window = {
    documentation = cmp.config.window.bordered(),
  },

2022-05-09 20:55 UTC, gnmearacaun approved these changes
we could fix this in master branch too

2022-05-31 19:38 UTC, gnmearacaun commented
#146 fixes this. If so you could close this PR

2022-06-01 01:28 UTC, aflyingpumpkin commented
Will do!

2022-06-01 01:28 UTC, closed without merging